server.port=8761

spring.application.name=eureka-server

# Eureka Server Configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Disable self-preservation in development
#eureka.server.enable-self-preservation=false
#eureka.server.eviction-interval-timer-in-ms=5000

# Reduce log noise
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF