spring.application.name=apiGateway

logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE
management.endpoints.web.exposure.include=*
management.endpoint.gateway.enabled=true

#JWT Key Config
jwt.secret.key=${JWT_SECRET_KEY}
jwt.expiration.hours=${JWT_EXPIRATION_HOURS}

#GateWay configuration
server.port=8080



#old routes
##routes config for auth -service
#spring.cloud.gateway.routes[0].id=auth-service
#spring.cloud.gateway.routes[0].uri=http://localhost:8083
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
#
##routes config for User-service
#spring.cloud.gateway.routes[1].id=user-service
#spring.cloud.gateway.routes[1].uri=http://localhost:8082
#spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**


#Web flux  routes config for auth-service
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

#routes config for User-service
spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/users/**

#Later after adding eureka
#add
#
#uri=lb://AUTH-SERVICE
#uri=lb://USER-SERVICE

# zipkin disable
spring.zipkin.enabled=false