spring.application.name=userService

server.port = 5001
spring.profiles.active=dev
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
logging.level.root=INFO

management.endpoints.web.exposure.include=health,info