


spring.datasource.url=jdbc:postgresql://localhost:5433/app_test_db
spring.datasource.username=app_user
spring.datasource.password=app_pass

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

logging.level.root=WARN