############################################
# APPLICATION
############################################
spring.application.name=User-service
server.port=8082

############################################
# DATASOURCE (Docker PostgreSQL)
############################################
spring.datasource.url=jdbc:postgresql://localhost:5433/FlowSync-UserService
spring.datasource.username=app_user
spring.datasource.password=app_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP (Connection Pool Tuning for Dev)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.pool-name=TaskServiceHikariPool

############################################
# JPA / HIBERNATE
############################################
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Better formatted SQL logs
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

############################################
# LOGGING (Development Friendly)
############################################
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.security=DEBUG

############################################
# ACTUATOR (Future Ready)
############################################
#management.endpoints.web.exposure.include=health,info
#management.endpoint.health.show-details=always

# Hibernate statistics (VERY IMPORTANT for N+1)
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=DEBUG

# Slow query detection
spring.jpa.properties.hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS=13