spring.application.name=auth-service

server.port = 8083

#Jwt secret key --- Stored in .env file
jwt.secret.key=${JWT_SECRET_KEY}
jwt.expiration.hours=${JWT_EXPIRATION_HOURS}



spring.datasource.url=jdbc:postgresql://localhost:5433/FlowSync-AuthService
#spring.datasource.username=app_user
#spring.datasource.password=app_pass

spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_USER_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Slow query detection
spring.jpa.properties.hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS=13